Dashboard: Remove convertEastNorthToNorthEast
Use of convertEastNorthToNorthEast in dashboard resulted in:

Valid parkings fetch failed:
TypeError: Cannot read properties of null (reading 'coordinates')
    at convertEastNorthToNorthEast (converters.ts:63)
    at convertParking (converters.ts:38)
...
which made regions not show up in the dashboard at all.

Remove convertEastNorthToNorthEast completely from dashboard. This makes
the regions show up in the dashboard with correct looking geometry.