Dashboard: Add react-bootstrap-table-next types
Dashboard previously failed to compile because of missing types for
react-bootstrap-table-next giving a TypeScript error TS7016. Adding the
missing types for react-bootstrap-table-next removes this error.