Dashboard: Add react-bootstrap-table2-paginator types
Dashboard previously failed to compile because of missing types for
react-bootstrap-table2-paginator giving a TypeScript error TS7016.
Adding the missing types for react-bootstrap-table2-paginator removes
this error.