Make dashboard compile by fixing TS2739 and TS2345
1. Description of TypeScript error TS2739:

TypeScript error in dashboard/src/containers/Dashboard.tsx(86,22):
Type '{}' is missing the following properties from type
'Omit<ClassAttributes<BootstrapTable<object, unknown>> &
BootstrapTableProps<object, unknown>, never>': data, columns, keyField
TS2739
    84 |                     <TimeSelect />
    85 |                     <div className="margin-bottom-8" />
  > 86 |                     <LastParkingsTable />
       |                      ^
    87 |                 </div>
    88 |
    89 |                 <div style={{width: '16px'}}/>

Fix the above by not passing a null value to the connect function in
LastParkingsTable.ts but removing the mapDispatchToProps parameter from
that call.

2. Fix TypeScript error TS2345:

TypeScript error in dashboard/src/containers/LastParkingsTable.ts(74,9):
Argument of type '{ expandRowBgColor: string; sizePerPageList:
undefined[]; sizePerPage: number; page: number; showTotal: true; }' is
not assignable to parameter of type 'Partial<{ custom: boolean; page:
number; sizePerPage: number; totalSize: number; pageStartIndex: number;
paginationSize: number; showTotal: boolean; sizePerPageList: number[] |
{ text: string; value: number; }[]; withFirstAndLast: boolean;
alwaysShowAllBtns: boolean; firstPageText: string | Element;
prePageText: string | Element; nextPageText: string | Element;
lastPageText: string | Element; nextPageTitle: string; prePageTitle:
string; firstPageTitle: string; lastPageTitle: string; hideSizePerPage:
boolean; hidePageListOnlyOnePage: boolean; pageButtonRenderer: (options:
PageButtonRendererOptions) => Element; onPageChange: (page: number,
sizePerPage: number) => void; onSizePerPageChange: (page: number,
sizePerPage: number) => void; pageListRenderer: (options:
PageListRendererOptions) => Element; sizePerPageRenderer: (options:
SizePerPageRendererOptions) => Element; sizePerPageOptionRenderer:
(options: SizePerPageOptionRendererOptions) => Element;
paginationTotalRenderer: (from: number, to: number, size: number) =>
Element; }>'.
  Object literal may only specify known properties, and
  'expandRowBgColor' does not exist in type 'Partial<{ custom: boolean;
  page: number; sizePerPage: number; totalSize: number; pageStartIndex:
  number; paginationSize: number; showTotal: boolean; sizePerPageList:
  number[] | { text: string; value: number; }[]; withFirstAndLast:
  boolean; alwaysShowAllBtns: boolean; firstPageText: string | Element;
  prePageText: string | Element; nextPageText: string | Element;
  lastPageText: string | Element; nextPageTitle: string; prePageTitle:
  string; firstPageTitle: string; lastPageTitle: string;
  hideSizePerPage: boolean; hidePageListOnlyOnePage: boolean;
  pageButtonRenderer: (options: PageButtonRendererOptions) => Element;
  onPageChange: (page: number, sizePerPage: number) => void;
  onSizePerPageChange: (page: number, sizePerPage: number) => void;
  pageListRenderer: (options: PageListRendererOptions) => Element;
  sizePerPageRenderer: (options: SizePerPageRendererOptions) => Element;
  sizePerPageOptionRenderer: (options: SizePerPageOptionRendererOptions)
  => Element; paginationTotalRenderer: (from: number, to: number, size:
  number) => Element; }>'.

Fix the above by removing expandRowBgColor from the paginationFactory
call in LastParkingsTable.ts as it seems the type of the pagination
object has changed and does not include expandRowBgColor anymore.